version: '2'
services:
  dev:
    container_name: bar_interativo_db
    image: kiasaki/alpine-postgres:latest
    ports:
      - 32776:5432
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=barinterativo
      - PGDATA=/var/lib/postgresql/data

  test:
    container_name: bar_interativo_db_test
    image: kiasaki/alpine-postgres:latest
    ports:
      - 32775:5432
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=barinterativoservertest
      - PGDATA=/var/lib/postgresql/data
